### ISSUE TITLE
Max's Goals for Grab-Tag-Graph Code

### ISSUE THREAD

**Issue by MPWeiner** [kwhitehall/grab-tag-graph#48]
- Efficiency and Speedup of Data Ingestion
  - Read in all of the data, in parallel
  - Push it to the graph
  - Close the source files
  - **This is done to optimize memory usage during data read in**
- Parallelization and Optimization
  - Apply parallelization to data ingestion
  - Work on optimization of algorithm with Gabe, solving any possible code inefficiencies
- Existing Issues
  - Work to solve any issues existing in the code, including but not limited to tree traversal issues

**Comment by kwhitehall** [comment]
Dear Max,
Please start this task on serial optimization (great suggestion @meldefon!)
- find_MCC function in mccSearch.py
  *Profile the code
  *Please refactor that function into subsections if possible. Please remember to provide unittests where necessary. (Provide a unittest find_MCC as well)
  *Profile again after the refactoring
  *Provide an approach to reduce the inefficient section(s) found (serially or otherwise)

**Comment by MPWeiner** [comment]
Kim,

My repo is updated with recent progress and I have pushed a status write up. It can be found here. https://github.com/MPWeiner/grab-tag-graph/blob/master/status.md

**Comment by kwhitehall** [comment]
Nice @MPWeiner! Thank you for the comprehensive update. Can you please push your code, maybe in branch on your repo so that we can have a look?

**Comment by kwhitehall** [comment]
This code has been merge with PR #81. Thank you for your contributions to the codebase @MPWeiner!
